backend:
  name: github
  repo: john-rock/salty-skier-designs

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Projects
    folder: content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: datetime }
      - { name: tags, label: Tags, widget: "list", allow_add: true, hint: "Add tags to help organize projects. Each tag seperated by a comma.", required: false}
      - { name: description, label: Description }
      - { name: thumbnail, label: Thumbnail Image, widget: image, required: false }
      - { name: body, label: Body, widget: markdown }